// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// Cpp_BinCount_sorted
arma::uvec Cpp_BinCount_sorted(arma::vec x, arma::vec s);
RcppExport SEXP _mmnst_Cpp_BinCount_sorted(SEXP xSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(Cpp_BinCount_sorted(x, s));
    return rcpp_result_gen;
END_RCPP
}
// fast_first_index_vec_ordered_x
IntegerVector fast_first_index_vec_ordered_x(NumericVector x, NumericVector v);
RcppExport SEXP _mmnst_fast_first_index_vec_ordered_x(SEXP xSEXP, SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_first_index_vec_ordered_x(x, v));
    return rcpp_result_gen;
END_RCPP
}
// cpp_PoissonRDP
arma::vec cpp_PoissonRDP(arma::vec sig, double gamma);
RcppExport SEXP _mmnst_cpp_PoissonRDP(SEXP sigSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type sig(sigSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_PoissonRDP(sig, gamma));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mmnst_Cpp_BinCount_sorted", (DL_FUNC) &_mmnst_Cpp_BinCount_sorted, 2},
    {"_mmnst_fast_first_index_vec_ordered_x", (DL_FUNC) &_mmnst_fast_first_index_vec_ordered_x, 2},
    {"_mmnst_cpp_PoissonRDP", (DL_FUNC) &_mmnst_cpp_PoissonRDP, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_mmnst(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
