# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Cpp_BinCount_sorted <- function(x, s) {
    .Call(`_mmnst_Cpp_BinCount_sorted`, x, s)
}

fast_first_index_vec_ordered_x <- function(x, v) {
    .Call(`_mmnst_fast_first_index_vec_ordered_x`, x, v)
}

